
version: '3'

services:

  jenkins1:
    container_name: jenkins1
    build: ./jenkins/
    entrypoint: /bin/tini -- /usr/local/bin/jenkins.sh --prefix=/jenkins/
    ports:
      - "10001:8080"
      - "10002:50000"
    volumes:
      - ./jenkins1:/var/jenkins_home

  nexus1:
   container_name: nexus1
   build: nexus1
   environment:
      - CONTEXT_PATH=/nexus
   ports:
      - "10003:8081"
   volumes:
      - ./nexus1:/var/lib/nexus

  sonarpostgresql:
    container_name: sonarpostgresql
    image: orchardup/postgresql:latest
    environment:
      - POSTGRESQL_USER=sonar
      - POSTGRESQL_PASS=sonar
      - POSTGRESQL_DB=sonar
    volumes:
      - sonarqube1/:/var/lib/postgresql
    ports:
      - "10004:5432"

  sonarqube1:
     container_name: sonarqube1
     build: ./sonarqube1/
     links:
       - postgresql:db
     environment:
       - DB_USER=sonar
       - DB_PASS=sonar
       - DB_NAME=sonar
     ports:
       - "10005:9000"
       - "10006:443"

  reverseproxy1:
    container_name: reverseproxy1
    build: ./reverseproxy1/
    ports:
      - "10007:80"
    links:
      - nexus1
      - sonarqube1
      - jenkins1
      - jfrogartifactory1
      - gitlabce1

  jfrogartifactory1:
    container_name: jfrogartifactory1
    build: ./jfrogartifactory1/
    ports:
      - "10008:8080"
    volumes:
      - ./jfrogartifactory1/:/artifactory/


  gitlabce1:
    container_name: gitlabce1
    hostname: 'gitlab1.odcg.eu'
    build: ./gitlabce1/
    ports:
      - "10009:443"
      - "100010:80"
      - "100011:22"
    volumes:
      - ./gitlab1-etc/:/etc/gitlab
      - ./gitlab1-log/:/var/log/gitlab
      - ./gitlab1-otp/:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password


  gitlabrunner1:
    build: ./gitlabrunner1
    deploy:
      mode: replicated
      replicas: 2


  kiwitcms1:
    container_name: kiwitcms1
    build: ./kiwitcms1/
    ports:
      - "10012:8080"
    volumes:
      - ./jfrogartifactory1/:/artifactory/


  kiwitcms1maria1:
    container_name: kiwitcms1maria
    image: centos/mariadb
    volumes:
        - ./kiwitcms1maria:/var/lib/mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: olivier
        MYSQL_DATABASE: kiwi
        MYSQL_USER: kiwi
        MYSQL_PASSWORD: kiwi
        MYSQL_CHARSET: utf8
        MYSQL_COLLATION: utf8_unicode_ci


  kiwitcms1:
    container_name: kiwitcms1
    depends_on:
        - kiwitcms1maria1
    restart: always
    image: kiwitcms/kiwi:latest
    ports:
      - "10013:8080"
      - "10014:8443"
    volumes:
        - ./kiwitcms1:/Kiwi/uploads:Z
    environment:
        KIWI_DB_HOST: kiwitcms1maria1
        KIWI_DB_PORT: 3306
        KIWI_DB_NAME: kiwi
        KIWI_DB_USER: kiwi
        KIWI_DB_PASSWORD: kiwi



  kiwitcms1:
    container_name: kiwitcms1
    depends_on:
        - kiwitcms1maria1
    restart: always
    build: ./kiwitcms1
    ports:
      - "10013:8080"
      - "10014:8443"
    volumes:
        - ./kiwitcms1:/Kiwi/uploads:Z
    environment:
        KIWI_DB_HOST: kiwitcms1maria1
        KIWI_DB_PORT: 3306
        KIWI_DB_NAME: kiwi
        KIWI_DB_USER: kiwi
        KIWI_DB_PASSWORD: kiwi


  drone1:
    container_name: drone1
    restart: always
    build: ./drone1
    ports:
      - "10015:80"
    volumes:
        - ./drone1:/var/lib/drone



#selenium hub
#selenium
#drone

configs:
  gitlab:
    file: ./gitlab.rb

secrets:
  gitlab_root_password:
    file: ./root_password.txt



